### ISSUE TITLE
Inconsistency between function prototypes and implementation

### ISSUE THREAD

**Issue by khues** [CiscoDevNet/csmp-agent-lib#3]
The commit "d42a3ea" in the GitHub project causes various segmentation faults because function implementations have been changed without changing the prototypes in the corresponding header file or the callers of these functions. If this code is executed, these function calls cause segmentation faults. Example: ProtobufVarint_encodeUINT32. The reason why GCC does not throw compiler warnings and errors in these cases is that the .c file that contain the function implementation does not include the .h file that contains the function prototype. Therefore, we would strongly suggest to always include the corresponding header file in the .c files so that such errors are detected early by GCC.

**Comment by woobagooba** [comment]
Resolved by PR f640f9b May 24 2023.
